"""
test_orchestrator_v3.py - Comprehensive Unit & Integration Tests for Orchestrator Version 3 Autonomous Loop

Validates:
- Multiple task sequential execution within a single development day
- Retry flow invocation when code fails review or automated tests
- Commit flow with GitAgent on successful task completions
- State progression and history accumulation via StateManager
- Automatic day and phase completion when all daily tasks complete
- Project completion marking status="completed" when all plan phases finish
- Partial failures handling (one task fails, remaining tasks continue)
- Execution summary metrics accuracy (averages, durations, counts, file lists)
- Fatal error handling (missing plan, invalid configuration)
- Non-crashing exception resilience
"""

import json
import logging
from pathlib import Path
from unittest.mock import MagicMock, patch
import pytest

from agents.coder_agent import CoderAgent, GeneratedFile, GeneratedResult
from agents.file_writer_agent import FileWriterAgent, WriteResult
from agents.git_agent import CommitResult, GitAgent
from agents.reviewer_agent import Issue, ReviewerAgent, ReviewResult
from agents.task_planner_agent import Task, TaskPlannerAgent
from agents.tester_agent import TesterAgent, TestResult
from core.orchestrator import ExecutionSummary, Orchestrator
from core.retry_engine import RetryEngine, RetryResult
from core.state_manager import ProjectState, StateManager


@pytest.fixture
def multi_day_project_env(tmp_path: Path):
    """Sets up an isolated workspace, memory store, and multi-day project plan."""
    workspace = tmp_path / "workspace"
    workspace.mkdir(parents=True, exist_ok=True)

    memory_dir = tmp_path / "memory"
    memory_dir.mkdir(parents=True, exist_ok=True)

    logs_dir = tmp_path / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    plan_path = memory_dir / "project_plan.json"
    state_path = memory_dir / "state.json"
    tasks_path = memory_dir / "tasks.json"

    plan_data = {
        "project_name": "Multi-Task Autonomous App",
        "project_description": "V3 Autonomous Loop Testing",
        "technology_stack": "Python, Pytest",
        "total_days": 2,
        "phases": [
            {
                "day": 1,
                "phase_name": "Day 1 Setup & Config",
                "goals": ["Scaffold application", "Setup config"],
                "tasks": [
                    "Implement application entry point",
                    "Implement configuration loader",
                ],
                "deliverables": ["src/main.py", "src/config.py"],
                "testing_focus": "Unit testing",
                "git_commit_message": "feat: day 1 core",
            },
            {
                "day": 2,
                "phase_name": "Day 2 Business Logic",
                "goals": ["Build service layer"],
                "tasks": [
                    "Implement business logic service",
                ],
                "deliverables": ["src/service.py"],
                "testing_focus": "Integration testing",
                "git_commit_message": "feat: day 2 service",
            },
        ],
    }
    with open(plan_path, "w", encoding="utf-8") as f:
        json.dump(plan_data, f, indent=2)

    return {
        "workspace": workspace,
        "plan_path": plan_path,
        "state_path": state_path,
        "tasks_path": tasks_path,
        "logs_dir": logs_dir,
    }


# =============================================================================
# 1. Multiple Task Execution & Day Completion Tests
# =============================================================================

def test_multiple_task_execution_and_day_completion(multi_day_project_env):
    """Verifies that all pending tasks for Day 1 execute in sequence and advance day to Day 2."""
    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
    )

    summary = orch.run()

    assert isinstance(summary, ExecutionSummary)
    assert summary.overall_success is True
    # Day 1 has 3 tasks generated by deterministic planner (2 raw tasks + 1 validation task)
    assert len(summary.tasks_completed) >= 2
    assert len(summary.tasks_failed) == 0
    assert summary.current_day == 1
    assert summary.next_day == 2
    assert 1 in summary.state_after.completed_phases
    assert summary.state_after.current_day == 2
    assert summary.average_quality_score > 0
    assert summary.average_test_pass_rate >= 0.0
    assert len(summary.generated_files) > 0


# =============================================================================
# 2. State Progression & Subsequent Day Run Tests
# =============================================================================

def test_state_progression_across_days_to_project_completion(multi_day_project_env):
    """Verifies multi-day sequential execution until full project completion."""
    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
    )

    # Run Day 1 -> completes Day 1 and advances to Day 2
    summary_day1 = orch.run()
    assert summary_day1.overall_success is True
    assert summary_day1.current_day == 1
    assert summary_day1.next_day == 2

    # Run Day 2 -> completes Day 2 and marks project completed
    summary_day2 = orch.run()
    assert summary_day2.overall_success is True
    assert summary_day2.current_day == 2
    assert summary_day2.next_day is None
    assert summary_day2.status == "completed"
    assert 2 in summary_day2.state_after.completed_phases


# =============================================================================
# 3. Retry Flow Invocation Tests
# =============================================================================

def test_retry_flow_invoked_on_defect_or_test_failure(multi_day_project_env):
    """Verifies that low quality scores or test failures invoke the RetryEngine."""
    call_counts = {"review": 0, "retry": 0}

    class FlakyReviewer(ReviewerAgent):
        def review(self, context, generated_result, test_result=None):
            call_counts["review"] += 1
            # First task triggers retry via should_regenerate=True
            if call_counts["review"] == 1:
                return ReviewResult(
                    success=True,
                    summary="Needs work",
                    overall_quality_score=60,
                    should_regenerate=True,
                )
            return ReviewResult(
                success=True,
                summary="Good code",
                overall_quality_score=92,
                should_regenerate=False,
            )

    class MockRetryEngine(RetryEngine):
        def execute(self, context, task, max_attempts=None, minimum_quality_score=None):
            call_counts["retry"] += 1
            return RetryResult(
                success=True,
                attempts=2,
                max_attempts=3,
                final_generated_result=GeneratedResult(
                    summary="Regenerated",
                    files=[GeneratedFile(path="src/fixed.py", content="# fixed\n")],
                    explanation="Self-healed",
                ),
                final_test_result=TestResult(
                    success=True,
                    total_tests=1,
                    passed=1,
                    failed=0,
                    skipped=0,
                    duration=0.1,
                    stdout="1 passed in 0.10s",
                    stderr="",
                    exit_code=0,
                    command="pytest",
                    message="All tests passed.",
                ),
                final_review_result=ReviewResult(success=True, summary="Clean", overall_quality_score=90, should_regenerate=False),
            )

    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
        reviewer_agent=FlakyReviewer(),
        retry_engine=MockRetryEngine(),
    )

    summary = orch.run()
    assert call_counts["retry"] >= 1
    assert summary.overall_success is True


# =============================================================================
# 4. Git Commit Flow Tests
# =============================================================================

def test_git_commit_created_for_successful_tasks(multi_day_project_env):
    """Verifies that GitAgent commits changes for each successfully completed task."""
    git_commits = []

    class TrackingGitAgent(GitAgent):
        def commit(self, message=None, task=None, review_result=None, files_to_stage=None, allow_empty=False):
            commit_hash = f"abc{len(git_commits) + 1:04d}"
            git_commits.append(commit_hash)
            return CommitResult(
                success=True,
                commit_hash=commit_hash,
                commit_message=f"feat: completed {task.id if task else 'task'}",
                branch="main",
            )

    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
        git_agent=TrackingGitAgent(project_root=multi_day_project_env["workspace"], auto_init=False),
    )

    summary = orch.run()
    assert len(summary.commits_created) > 0
    assert len(summary.commits_created) == len(summary.tasks_completed)


# =============================================================================
# 5. Partial Failures & Loop Continuation Tests
# =============================================================================

def test_partial_task_failure_continues_remaining_tasks(multi_day_project_env):
    """Verifies that if one task fails, remaining tasks continue processing."""
    class SelectiveFailingCoder(CoderAgent):
        def execute(self, context, task):
            # TASK01 throws exception
            if task.id == "DAY1-TASK01":
                raise RuntimeError("LLM synthesis failure on Task 1")
            return GeneratedResult(
                summary="Success",
                files=[GeneratedFile(path="src/ok.py", content="# ok\n")],
                explanation="Done",
            )

    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
        coder_agent=SelectiveFailingCoder(),
    )

    summary = orch.run()

    # TASK01 should be in tasks_failed, while others succeed
    assert "DAY1-TASK01" in summary.tasks_failed
    assert len(summary.tasks_completed) >= 1
    assert summary.overall_success is False
    assert summary.next_day == 1  # Day does not advance because of failure


# =============================================================================
# 6. Execution Summary Accuracy Tests
# =============================================================================

def test_execution_summary_metrics_and_serialization(multi_day_project_env):
    """Verifies precision and accuracy of ExecutionSummary telemetry."""
    orch = Orchestrator(
        project_root=multi_day_project_env["workspace"],
        plan_path=multi_day_project_env["plan_path"],
        state_path=multi_day_project_env["state_path"],
        tasks_path=multi_day_project_env["tasks_path"],
        log_dir=multi_day_project_env["logs_dir"],
    )

    summary = orch.run()

    assert summary.execution_duration >= 0.0
    assert isinstance(summary.average_quality_score, float)
    assert 0.0 <= summary.average_quality_score <= 100.0
    assert 0.0 <= summary.average_test_pass_rate <= 100.0

    summary_dict = summary.to_dict()
    assert "overall_success" in summary_dict
    assert "tasks_completed" in summary_dict
    assert "tasks_failed" in summary_dict
    assert "average_quality_score" in summary_dict
    assert "execution_duration" in summary_dict


# =============================================================================
# 7. Fatal Error Handling (Missing Plan)
# =============================================================================

def test_missing_plan_error_handling(tmp_path: Path):
    """Verifies that missing plan returns overall_success=False without crashing."""
    orch = Orchestrator(
        project_root=tmp_path / "ws",
        plan_path=tmp_path / "nonexistent_plan.json",
        state_path=tmp_path / "state.json",
        tasks_path=tmp_path / "tasks.json",
        log_dir=tmp_path / "logs",
    )

    summary = orch.run()
    assert summary.overall_success is False
    assert "missing" in summary.error.lower() or "not found" in summary.error.lower()
    assert summary.status == "failed"
