"""
coder_agent.py - Coder Agent for AutoDev

Responsible for executing a single atomic engineering task by constructing
an engineering prompt, querying the configured BaseLLM provider, and validating
the resulting structured JSON code generation payload into a GeneratedResult.
"""

from __future__ import annotations

import json
import logging
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# Ensure project root is available on sys.path for direct execution
if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.task_planner_agent import Task
from core.llm import BaseLLM, MockLLM
from core.prompt_builder import PromptBuilder

# Module logger
logger = logging.getLogger("AutoDev.CoderAgent")


class CoderValidationError(ValueError):
    """
    Raised when an LLM response fails validation against the required JSON schema.
    """
    pass


@dataclass
class GeneratedFile:
    """
    Represents an individual source code file generated by the CoderAgent.
    """
    path: str
    content: str

    def to_dict(self) -> Dict[str, str]:
        """Converts file entry to dictionary representation."""
        return {"path": self.path, "content": self.content}


@dataclass
class GeneratedResult:
    """
    Validated code generation result for an atomic engineering task.
    """
    summary: str
    files: List[GeneratedFile]
    explanation: str

    def to_dict(self) -> Dict[str, Any]:
        """Converts result to a serializable dictionary."""
        return {
            "summary": self.summary,
            "files": [f.to_dict() for f in self.files],
            "explanation": self.explanation,
        }


def _create_default_mock_response() -> str:
    """Creates a valid JSON mock response string for offline dry runs."""
    payload = {
        "summary": "Scaffolded project baseline entry point and configuration management.",
        "files": [
            {
                "path": "src/main.py",
                "content": "# Entry point for target application\n\ndef main():\n    print('Application started successfully.')\n\nif __name__ == '__main__':\n    main()\n",
            },
            {
                "path": "src/config.py",
                "content": "# Application configuration settings\n\nAPP_NAME = 'AutoDev Project'\nVERSION = '0.1.0'\nDEBUG = True\n",
            }
        ],
        "explanation": "Created entry point in src/main.py and default settings in src/config.py adhering to project architecture."
    }
    return json.dumps(payload, indent=2)


class CoderAgent:
    """
    Executes atomic engineering tasks through provider-agnostic BaseLLM models.
    """

    def __init__(
        self,
        llm: Optional[BaseLLM] = None,
        prompt_builder: Optional[PromptBuilder] = None,
    ) -> None:
        """
        Initializes the CoderAgent.

        Args:
            llm: BaseLLM implementation (defaults to MockLLM with valid JSON response).
            prompt_builder: PromptBuilder instance (defaults to standard PromptBuilder).
        """
        self.llm: BaseLLM = llm or MockLLM(default_response=_create_default_mock_response())
        self.prompt_builder: PromptBuilder = prompt_builder or PromptBuilder()

    def _extract_json(self, raw_response: str) -> Dict[str, Any]:
        """
        Extracts and parses JSON from raw LLM text, stripping markdown fences if present.

        Args:
            raw_response: Raw text returned by the language model.

        Returns:
            Parsed dictionary payload.

        Raises:
            CoderValidationError: If parsing fails.
        """
        cleaned = raw_response.strip()

        # Remove markdown code fences (```json ... ``` or ``` ... ```)
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
            cleaned = re.sub(r"\s*```$", "", cleaned)
            cleaned = cleaned.strip()

        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError as exc:
            logger.error("Failed to parse LLM response as JSON: %s", exc)
            raise CoderValidationError(
                f"LLM response is not valid JSON: {exc}\nRaw Response Preview: {raw_response[:300]}"
            ) from exc

        if not isinstance(parsed, dict):
            raise CoderValidationError(
                f"Expected top-level JSON object (dict), but received {type(parsed).__name__}."
            )

        return parsed

    def _validate_payload(self, data: Dict[str, Any]) -> GeneratedResult:
        """
        Validates the parsed dictionary against the required output schema.

        Args:
            data: Parsed dictionary from LLM output.

        Returns:
            Validated GeneratedResult instance.

        Raises:
            CoderValidationError: If required fields or file structures are missing/invalid.
        """
        # Validate summary
        if "summary" not in data:
            raise CoderValidationError("Missing required field 'summary' in LLM output.")
        if not isinstance(data["summary"], str) or not data["summary"].strip():
            raise CoderValidationError("Field 'summary' must be a non-empty string.")

        # Validate explanation
        if "explanation" not in data:
            raise CoderValidationError("Missing required field 'explanation' in LLM output.")
        if not isinstance(data["explanation"], str) or not data["explanation"].strip():
            raise CoderValidationError("Field 'explanation' must be a non-empty string.")

        # Validate files list
        if "files" not in data:
            raise CoderValidationError("Missing required field 'files' in LLM output.")
        if not isinstance(data["files"], list):
            raise CoderValidationError("Field 'files' must be a list of file objects.")

        validated_files: List[GeneratedFile] = []
        for index, item in enumerate(data["files"]):
            if not isinstance(item, dict):
                raise CoderValidationError(
                    f"Item at files[{index}] must be a dict object, got {type(item).__name__}."
                )

            if "path" not in item:
                raise CoderValidationError(f"File at index {index} is missing required 'path' field.")
            if not isinstance(item["path"], str) or not item["path"].strip():
                raise CoderValidationError(f"File at index {index} 'path' must be a non-empty string.")

            if "content" not in item:
                raise CoderValidationError(f"File '{item['path']}' is missing required 'content' field.")
            if not isinstance(item["content"], str):
                raise CoderValidationError(f"File '{item['path']}' 'content' must be a string.")

            validated_files.append(
                GeneratedFile(
                    path=item["path"].strip(),
                    content=item["content"],
                )
            )

        return GeneratedResult(
            summary=data["summary"].strip(),
            files=validated_files,
            explanation=data["explanation"].strip(),
        )

    def execute(
        self,
        context: Dict[str, Any],
        task: Union[Task, Dict[str, Any]],
    ) -> GeneratedResult:
        """
        Executes a single atomic engineering task.

        Args:
            context: Context dictionary produced by ContextBuilder.
            task: Task object or dictionary produced by TaskPlannerAgent.

        Returns:
            Validated GeneratedResult containing generated files and explanations.
        """
        task_id = task.id if isinstance(task, Task) else task.get("id", "UNKNOWN")
        task_title = task.title if isinstance(task, Task) else task.get("title", "Untitled Task")

        logger.info("CoderAgent starting task [%s]: %s", task_id, task_title)

        # Step 1: Synthesize engineering prompt
        logger.info("Synthesizing engineering prompt with PromptBuilder...")
        prompt = self.prompt_builder.build(context=context, task=task)

        # Step 2: Query BaseLLM
        logger.info("Dispatching prompt to %s...", type(self.llm).__name__)
        raw_response = self.llm.generate(prompt)

        # Step 3 & 4: Extract and validate JSON response
        logger.info("Validating structured JSON response...")
        parsed_payload = self._extract_json(raw_response)
        result = self._validate_payload(parsed_payload)

        logger.info(
            "Task [%s] completed successfully. Generated %d file(s).",
            task_id,
            len(result.files),
        )

        return result


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)-5s] %(message)s")

    from agents.task_planner_agent import TaskPlannerAgent
    from core.context_builder import build_context

    # 1. Load context
    ctx = build_context()

    # 2. Plan tasks
    planner = TaskPlannerAgent()
    tasks = planner.execute(ctx)
    first_task = tasks[0] if tasks else Task(
        id="DAY1-TASK01",
        title="Initialize project scaffold",
        description="Create basic structure and entry point.",
    )

    # 3. Instantiate CoderAgent with MockLLM
    agent = CoderAgent()
    generated = agent.execute(context=ctx, task=first_task)

    print("\n" + "=" * 60)
    print("               CODER AGENT EXECUTION RESULT")
    print("=" * 60)
    print(f"Summary     : {generated.summary}")
    print(f"Files Count : {len(generated.files)}")
    for f in generated.files:
        print(f"  - File: {f.path} ({len(f.content)} bytes)")
    print(f"\nExplanation : {generated.explanation}")
    print("=" * 60 + "\n")
