"""
reviewer_agent.py - AI-Powered Code Review Agent for AutoDev

Responsible for analyzing code generated by CoderAgent alongside test execution metrics
from TesterAgent against project context, evaluating quality, detecting issues,
scoring overall codebase quality, and determining if regeneration is required.
"""

from __future__ import annotations

import json
import logging
import re
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# Ensure project root is available on sys.path for direct execution
if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.coder_agent import GeneratedFile, GeneratedResult
from agents.tester_agent import TestResult
from core.llm import BaseLLM, MockLLM

# Module logger
logger = logging.getLogger("AutoDev.ReviewerAgent")


class ReviewValidationError(ValueError):
    """
    Raised when an LLM review response fails validation against the required schema.
    """
    pass


VALID_SEVERITIES = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}


@dataclass
class Issue:
    """
    Represents an individual code quality, architectural, or security finding.
    """
    severity: str
    category: str
    file: str
    line: Optional[int]
    description: str
    recommendation: str

    def to_dict(self) -> Dict[str, Any]:
        """Converts issue to dictionary representation."""
        return asdict(self)


@dataclass
class ReviewResult:
    """
    Structured outcome of the AI code review pipeline.
    """
    success: bool
    summary: str
    overall_quality_score: int
    issues: List[Issue] = field(default_factory=list)
    strengths: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    should_regenerate: bool = False
    explanation: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Converts review result to dictionary representation."""
        return {
            "success": self.success,
            "summary": self.summary,
            "overall_quality_score": self.overall_quality_score,
            "issues": [i.to_dict() for i in self.issues],
            "strengths": self.strengths,
            "recommendations": self.recommendations,
            "should_regenerate": self.should_regenerate,
            "explanation": self.explanation,
        }


def _create_default_mock_review_response() -> str:
    """Creates a valid JSON mock review response string for offline dry runs."""
    payload = {
        "success": True,
        "summary": "The generated modules are well-structured, follow SOLID principles, and pass all automated tests.",
        "overall_quality_score": 92,
        "issues": [
            {
                "severity": "LOW",
                "category": "Documentation",
                "file": "src/main.py",
                "line": 1,
                "description": "Consider adding more detailed module-level docstrings.",
                "recommendation": "Expand module docstring with usage examples.",
            }
        ],
        "strengths": [
            "Clean separation of concerns",
            "Full type annotations included",
            "All unit tests executing successfully",
        ],
        "recommendations": [
            "Add integration test coverage in future phase",
        ],
        "should_regenerate": False,
        "explanation": "Code meets production standards. No blocking issues detected.",
    }
    return json.dumps(payload, indent=2)


class ReviewPromptBuilder:
    """
    Constructs comprehensive code review prompts combining project context,
    generated code files, and test runner telemetry.
    """

    def build_prompt(
        self,
        context: Dict[str, Any],
        generated_result: GeneratedResult,
        test_result: Optional[TestResult] = None,
    ) -> str:
        """
        Synthesizes a structured review prompt.

        Args:
            context: Project context dictionary from ContextBuilder.
            generated_result: GeneratedResult from CoderAgent.
            test_result: Optional TestResult from TesterAgent.

        Returns:
            Complete review prompt string.
        """
        project_name = context.get("project_name", "AutoDev Project")
        description = context.get("description", "No description provided.")
        tech_stack = context.get("technology_stack", "Standard Library")
        current_day = context.get("current_day", 1)
        current_phase = context.get("current_phase", {}) or {}
        phase_name = current_phase.get("phase_name", f"Day {current_day} Phase")

        # Format generated files
        files_section_parts: List[str] = []
        for file in generated_result.files:
            files_section_parts.append(
                f"--- File: {file.path} ---\n{file.content}\n--- End of File ---"
            )
        files_text = "\n\n".join(files_section_parts) if files_section_parts else "(No files generated)"

        # Format test execution telemetry
        if test_result is not None:
            test_telemetry = (
                f"Test Suite Success  : {test_result.success}\n"
                f"Total Tests Run     : {test_result.total_tests}\n"
                f"Passed Tests        : {test_result.passed}\n"
                f"Failed Tests        : {test_result.failed}\n"
                f"Skipped Tests       : {test_result.skipped}\n"
                f"Execution Duration  : {test_result.duration}s\n"
                f"Exit Code           : {test_result.exit_code}\n"
                f"Test Summary        : {test_result.message}\n"
                f"Stdout Preview      : {test_result.stdout[:500] if test_result.stdout else 'None'}\n"
                f"Stderr Preview      : {test_result.stderr[:500] if test_result.stderr else 'None'}"
            )
        else:
            test_telemetry = "(No automated test telemetry available for this review cycle)"

        prompt = f"""================================================================================
1. SYSTEM ROLE: PRINCIPAL CODE REVIEWER & ARCHITECT
================================================================================
You are the Lead Code Reviewer and Principal Architect in the AutoDev autonomous platform.
Your responsibility is to critically evaluate newly generated code against project
requirements, architecture standards, SOLID principles, security guidelines, and test results.

================================================================================
2. PROJECT & PHASE CONTEXT
================================================================================
Project Name  : {project_name}
Description   : {description}
Tech Stack    : {tech_stack}
Active Day    : Day {current_day}
Active Phase  : {phase_name}

================================================================================
3. CODER AGENT GENERATION SUMMARY
================================================================================
Summary       : {generated_result.summary}
Explanation   : {generated_result.explanation}

================================================================================
4. GENERATED SOURCE CODE FILES
================================================================================
{files_text}

================================================================================
5. TEST RUNNER TELEMETRY
================================================================================
{test_telemetry}

================================================================================
6. REVIEW CRITERIA
================================================================================
1. Requirement Alignment : Does the code fulfill the phase goals and task requirements?
2. Architectural Design  : Does it follow clean modular structure and SOLID principles?
3. Reliability & Tests   : Are edge cases handled, and are test failures addressed?
4. Security & Safety     : Are there obvious security risks, injections, or resource leaks?
5. Code Quality          : Are there clear type annotations, docstrings, and robust error handling?
6. Regeneration Decision : Set 'should_regenerate' to true ONLY if there are critical, blocking defects.

================================================================================
7. REQUIRED JSON OUTPUT FORMAT
================================================================================
You MUST respond with a single valid JSON object strictly matching this schema:

{{
  "success": true,
  "summary": "Concise summary of the code review findings",
  "overall_quality_score": 90,
  "issues": [
    {{
      "severity": "LOW",
      "category": "Documentation",
      "file": "src/main.py",
      "line": 1,
      "description": "Detailed explanation of the issue found",
      "recommendation": "Actionable recommendation to resolve the issue"
    }}
  ],
  "strengths": [
    "List of strong architectural decisions and well-written components"
  ],
  "recommendations": [
    "List of future improvement suggestions"
  ],
  "should_regenerate": false,
  "explanation": "Comprehensive overall architectural rationale for the review outcome"
}}

Severity levels MUST be one of: LOW, MEDIUM, HIGH, CRITICAL.
Overall quality score MUST be an integer between 0 and 100.
Do NOT wrap the JSON in markdown fences. Return pure JSON only."""
        return prompt


class ReviewerAgent:
    """
    AI-driven Code Review Agent that analyzes code deliverables and test outcomes.
    """

    def __init__(
        self,
        llm: Optional[BaseLLM] = None,
        prompt_builder: Optional[ReviewPromptBuilder] = None,
    ) -> None:
        """
        Initializes the ReviewerAgent.

        Args:
            llm: BaseLLM provider instance (defaults to MockLLM with valid review output).
            prompt_builder: ReviewPromptBuilder instance.
        """
        self.llm: BaseLLM = llm or MockLLM(default_response=_create_default_mock_review_response())
        self.prompt_builder: ReviewPromptBuilder = prompt_builder or ReviewPromptBuilder()

    def _extract_json(self, raw_response: str) -> Dict[str, Any]:
        """
        Extracts and parses JSON from raw LLM text, stripping markdown code fences if present.

        Args:
            raw_response: Raw text returned by language model.

        Returns:
            Parsed dictionary payload.

        Raises:
            ReviewValidationError: If parsing fails or output is not a JSON object.
        """
        cleaned = raw_response.strip()

        # Remove markdown fences (```json ... ``` or ``` ... ```)
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
            cleaned = re.sub(r"\s*```$", "", cleaned)
            cleaned = cleaned.strip()

        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError as exc:
            logger.error("Failed to parse review response as JSON: %s", exc)
            raise ReviewValidationError(
                f"Reviewer LLM response is not valid JSON: {exc}\nRaw Response Preview: {raw_response[:300]}"
            ) from exc

        if not isinstance(parsed, dict):
            raise ReviewValidationError(
                f"Expected top-level JSON object (dict), but received {type(parsed).__name__}."
            )

        return parsed

    def _validate_payload(self, data: Dict[str, Any]) -> ReviewResult:
        """
        Validates the parsed review payload against the ReviewResult schema.

        Args:
            data: Parsed dictionary from LLM response.

        Returns:
            Validated ReviewResult instance.

        Raises:
            ReviewValidationError: If schema rules or field requirements are violated.
        """
        # Validate summary
        if "summary" not in data:
            raise ReviewValidationError("Missing required field 'summary' in review output.")
        if not isinstance(data["summary"], str) or not data["summary"].strip():
            raise ReviewValidationError("Field 'summary' must be a non-empty string.")

        # Validate overall_quality_score
        if "overall_quality_score" not in data:
            raise ReviewValidationError("Missing required field 'overall_quality_score' in review output.")
        score = data["overall_quality_score"]
        if isinstance(score, bool) or not isinstance(score, int):
            raise ReviewValidationError(
                f"Field 'overall_quality_score' must be an integer (0-100), got {type(score).__name__}."
            )
        if not (0 <= score <= 100):
            raise ReviewValidationError(
                f"Field 'overall_quality_score' must be between 0 and 100, got {score}."
            )

        # Validate should_regenerate
        if "should_regenerate" not in data:
            raise ReviewValidationError("Missing required field 'should_regenerate' in review output.")
        if not isinstance(data["should_regenerate"], bool):
            raise ReviewValidationError(
                f"Field 'should_regenerate' must be a boolean (True/False), got {type(data['should_regenerate']).__name__}."
            )

        # Validate explanation
        if "explanation" not in data:
            raise ReviewValidationError("Missing required field 'explanation' in review output.")
        if not isinstance(data["explanation"], str):
            raise ReviewValidationError("Field 'explanation' must be a string.")

        # Validate strengths
        strengths_raw = data.get("strengths", [])
        if not isinstance(strengths_raw, list):
            raise ReviewValidationError("Field 'strengths' must be a list of strings.")
        strengths = [str(s) for s in strengths_raw]

        # Validate recommendations
        recs_raw = data.get("recommendations", [])
        if not isinstance(recs_raw, list):
            raise ReviewValidationError("Field 'recommendations' must be a list of strings.")
        recommendations = [str(r) for r in recs_raw]

        # Validate issues
        issues_raw = data.get("issues", [])
        if not isinstance(issues_raw, list):
            raise ReviewValidationError("Field 'issues' must be a list of issue objects.")

        validated_issues: List[Issue] = []
        for index, item in enumerate(issues_raw):
            if not isinstance(item, dict):
                raise ReviewValidationError(
                    f"Item at issues[{index}] must be a dict object, got {type(item).__name__}."
                )

            severity = str(item.get("severity", "LOW")).strip().upper()
            if severity not in VALID_SEVERITIES:
                valid_str = ", ".join(sorted(VALID_SEVERITIES))
                raise ReviewValidationError(
                    f"Issue at index {index} has invalid severity '{severity}'. Must be one of: {valid_str}."
                )

            category = str(item.get("category", "General")).strip()
            file_path = str(item.get("file", "unknown")).strip()
            description = str(item.get("description", "")).strip()
            recommendation = str(item.get("recommendation", "")).strip()
            line_val = item.get("line")
            line_num: Optional[int] = int(line_val) if line_val is not None and not isinstance(line_val, bool) and str(line_val).isdigit() else None

            if not description:
                raise ReviewValidationError(f"Issue at index {index} must contain a non-empty 'description'.")

            validated_issues.append(
                Issue(
                    severity=severity,
                    category=category,
                    file=file_path,
                    line=line_num,
                    description=description,
                    recommendation=recommendation,
                )
            )

        success = data.get("success", True)
        if not isinstance(success, bool):
            success = True

        return ReviewResult(
            success=success,
            summary=data["summary"].strip(),
            overall_quality_score=score,
            issues=validated_issues,
            strengths=strengths,
            recommendations=recommendations,
            should_regenerate=data["should_regenerate"],
            explanation=data["explanation"].strip(),
        )

    def review(
        self,
        context: Dict[str, Any],
        generated_result: GeneratedResult,
        test_result: Optional[TestResult] = None,
    ) -> ReviewResult:
        """
        Executes code review by synthesizing the prompt, querying LLM, and validating output.

        Args:
            context: Project context dictionary.
            generated_result: GeneratedResult output from CoderAgent.
            test_result: Optional TestResult output from TesterAgent.

        Returns:
            Validated ReviewResult object.
        """
        logger.info("ReviewerAgent starting review of %d generated file(s)...", len(generated_result.files))

        # Step 1: Synthesize review prompt
        prompt = self.prompt_builder.build_prompt(
            context=context,
            generated_result=generated_result,
            test_result=test_result,
        )

        # Step 2: Query BaseLLM
        logger.info("Dispatching review prompt to %s...", type(self.llm).__name__)
        raw_response = self.llm.generate(prompt)

        # Step 3 & 4: Extract and validate JSON
        logger.info("Validating structured review response...")
        parsed_data = self._extract_json(raw_response)
        review_result = self._validate_payload(parsed_data)

        logger.info(
            "Review completed. Quality Score: %d/100, Issues: %d, Regenerate: %s",
            review_result.overall_quality_score,
            len(review_result.issues),
            review_result.should_regenerate,
        )

        return review_result


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)-5s] %(message)s")

    from core.context_builder import build_context

    ctx = build_context()
    dummy_gen = GeneratedResult(
        summary="Implemented project starter modules",
        files=[
            GeneratedFile(path="src/main.py", content="def main(): print('Hello AutoDev')\n"),
            GeneratedFile(path="src/config.py", content="DEBUG = True\n"),
        ],
        explanation="Created entry point and config files.",
    )
    dummy_test = TestResult(
        success=True,
        total_tests=2,
        passed=2,
        failed=0,
        skipped=0,
        duration=0.15,
        stdout="2 passed in 0.15s",
        stderr="",
        exit_code=0,
        command="pytest",
        message="All tests passed.",
    )

    reviewer = ReviewerAgent()
    result = reviewer.review(context=ctx, generated_result=dummy_gen, test_result=dummy_test)

    print("\n" + "=" * 60)
    print("               REVIEWER AGENT EXECUTION RESULT")
    print("=" * 60)
    print(f"Summary         : {result.summary}")
    print(f"Quality Score   : {result.overall_quality_score}/100")
    print(f"Regenerate Flag : {result.should_regenerate}")
    print(f"Issues Found    : {len(result.issues)}")
    for issue in result.issues:
        print(f"  [{issue.severity}] {issue.file}:{issue.line} - {issue.description}")
    print("\nStrengths:")
    for s in result.strengths:
        print(f"  + {s}")
    print("\nRecommendations:")
    for r in result.recommendations:
        print(f"  * {r}")
    print(f"\nExplanation     : {result.explanation}")
    print("=" * 60 + "\n")
