"""
task_queue_manager.py - Task Queue and Dependency Lifecycle Manager for AutoDev

Responsible for managing the execution queue, lifecycle transitions, dependency resolution,
and persistence of atomic development tasks generated by TaskPlannerAgent.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Union

logger = logging.getLogger("AutoDev.TaskQueueManager")


class TaskPriority(str, Enum):
    """Enumeration of valid task priority levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TaskState(str, Enum):
    """Enumeration of valid task lifecycle statuses."""
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"


# Priority ranks for ordering (lower numeric rank = higher dispatch priority)
PRIORITY_RANKS: Dict[str, int] = {
    TaskPriority.CRITICAL.value: 0,
    TaskPriority.HIGH.value: 1,
    TaskPriority.MEDIUM.value: 2,
    TaskPriority.LOW.value: 3,
}

VALID_STATUSES: Set[str] = {state.value for state in TaskState}
VALID_PRIORITIES: Set[str] = {p.value for p in TaskPriority}


# =============================================================================
# Custom Exception Hierarchy
# =============================================================================

class TaskQueueError(Exception):
    """Base exception for all TaskQueueManager operations."""
    pass


class TaskNotFoundError(TaskQueueError):
    """Raised when an operation references a non-existent task ID."""
    pass


class DuplicateTaskIdError(TaskQueueError):
    """Raised when multiple tasks declare the exact same identifier."""
    pass


class MissingDependencyError(TaskQueueError):
    """Raised when a task references a dependency ID not present in the task list."""
    pass


class CyclicDependencyError(TaskQueueError):
    """Raised when a circular dependency chain is detected among tasks."""
    pass


class InvalidPriorityError(TaskQueueError):
    """Raised when a task specifies an unsupported priority level."""
    pass


class InvalidStatusError(TaskQueueError):
    """Raised when a task specifies an unsupported status value."""
    pass


class TaskValidationError(TaskQueueError):
    """Raised when a task schema or metadata fails general validation rules."""
    pass


# =============================================================================
# Task Data Model
# =============================================================================

@dataclass
class TaskStatus:
    """
    Represents the queue state, lifecycle metadata, and execution parameters of an atomic task.
    """
    id: str
    title: str
    priority: str = TaskPriority.MEDIUM.value
    dependencies: List[str] = field(default_factory=list)
    status: str = TaskState.PENDING.value
    retry_count: int = 0
    max_retries: int = 3
    created_at: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))
    description: str = ""
    estimated_files: List[str] = field(default_factory=list)
    estimated_duration: str = "15 min"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Normalizes and verifies fields upon instantiation."""
        self.priority = str(self.priority).upper().strip()
        self.status = str(self.status).upper().strip()
        if not isinstance(self.dependencies, list):
            self.dependencies = list(self.dependencies)

    def to_dict(self) -> Dict[str, Any]:
        """Converts task status to a serializable dictionary."""
        return {
            "id": self.id,
            "title": self.title,
            "priority": self.priority,
            "dependencies": list(self.dependencies),
            "status": self.status,
            "retry_count": self.retry_count,
            "max_retries": self.max_retries,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "description": self.description,
            "estimated_files": list(self.estimated_files),
            "estimated_duration": self.estimated_duration,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> TaskStatus:
        """
        Creates a TaskStatus instance from a dictionary representation.
        """
        if not isinstance(data, dict):
            raise TaskValidationError(f"Expected dict for task deserialization, got {type(data).__name__}.")

        if "id" not in data or not str(data["id"]).strip():
            raise TaskValidationError("Task data is missing required 'id' field.")
        if "title" not in data or not str(data["title"]).strip():
            raise TaskValidationError(f"Task '{data.get('id')}' is missing required 'title' field.")

        now_str = datetime.now().isoformat(timespec="seconds")
        return cls(
            id=str(data["id"]).strip(),
            title=str(data["title"]).strip(),
            priority=str(data.get("priority", TaskPriority.MEDIUM.value)).upper().strip(),
            dependencies=[str(dep).strip() for dep in data.get("dependencies", [])],
            status=str(data.get("status", TaskState.PENDING.value)).upper().strip(),
            retry_count=int(data.get("retry_count", 0)),
            max_retries=int(data.get("max_retries", 3)),
            created_at=str(data.get("created_at", now_str)),
            updated_at=str(data.get("updated_at", now_str)),
            description=str(data.get("description", "")),
            estimated_files=[str(f) for f in data.get("estimated_files", [])],
            estimated_duration=str(data.get("estimated_duration", "15 min")),
            metadata=dict(data.get("metadata", {})),
        )


# =============================================================================
# TaskQueueManager Subsystem
# =============================================================================

class TaskQueueManager:
    """
    Manages the lifecycle, priority queueing, dependency resolution,
    and atomic persistence of atomic tasks generated by TaskPlannerAgent.
    """

    def __init__(
        self,
        tasks_path: Union[str, Path] = "memory/tasks.json",
        auto_load: bool = True,
        auto_create: bool = True,
    ) -> None:
        """
        Initializes the TaskQueueManager.

        Args:
            tasks_path: Path to the tasks JSON file (default: memory/tasks.json).
            auto_load: Whether to automatically load tasks from disk on initialization.
            auto_create: Whether to create an empty tasks file if it does not exist.
        """
        self.tasks_path = Path(tasks_path).resolve()
        self.auto_create = auto_create
        self._tasks: List[TaskStatus] = []
        self._task_map: Dict[str, TaskStatus] = {}

        if auto_load:
            if self.tasks_path.is_file():
                self.load_tasks()
            elif self.auto_create:
                self.tasks_path.parent.mkdir(parents=True, exist_ok=True)
                self.save_tasks()

    # -------------------------------------------------------------------------
    # Validation & Graph Algorithms
    # -------------------------------------------------------------------------

    def validate_tasks(self, tasks: Optional[List[TaskStatus]] = None) -> None:
        """
        Validates task integrity, unique IDs, priority/status schemas,
        missing dependency references, and cyclic dependencies.

        Args:
            tasks: Optional task list to validate (defaults to self._tasks).

        Raises:
            DuplicateTaskIdError: If duplicate task IDs exist.
            InvalidPriorityError: If an unsupported priority is found.
            InvalidStatusError: If an unsupported status is found.
            MissingDependencyError: If a dependency ID does not exist in the task list.
            CyclicDependencyError: If circular dependencies are discovered.
            TaskValidationError: If invalid field types or retry bounds are encountered.
        """
        target_tasks = tasks if tasks is not None else self._tasks
        seen_ids: Set[str] = set()
        task_id_set: Set[str] = set()

        # Step 1: Check basic fields, duplicates, priorities, and statuses
        for task in target_tasks:
            if not isinstance(task, TaskStatus):
                raise TaskValidationError(f"Expected TaskStatus instance, got {type(task).__name__}.")

            if not task.id or not isinstance(task.id, str):
                raise TaskValidationError("Task ID must be a non-empty string.")

            if task.id in seen_ids:
                raise DuplicateTaskIdError(f"Duplicate task ID detected: '{task.id}'.")
            seen_ids.add(task.id)
            task_id_set.add(task.id)

            if task.priority not in VALID_PRIORITIES:
                raise InvalidPriorityError(
                    f"Invalid priority '{task.priority}' for task '{task.id}'. "
                    f"Must be one of {sorted(VALID_PRIORITIES)}."
                )

            if task.status not in VALID_STATUSES:
                raise InvalidStatusError(
                    f"Invalid status '{task.status}' for task '{task.id}'. "
                    f"Must be one of {sorted(VALID_STATUSES)}."
                )

            if not isinstance(task.retry_count, int) or task.retry_count < 0:
                raise TaskValidationError(f"Task '{task.id}' retry_count must be non-negative integer.")

            if not isinstance(task.max_retries, int) or task.max_retries < 0:
                raise TaskValidationError(f"Task '{task.id}' max_retries must be non-negative integer.")

        # Step 2: Validate missing dependencies
        for task in target_tasks:
            for dep_id in task.dependencies:
                if dep_id not in task_id_set:
                    raise MissingDependencyError(
                        f"Task '{task.id}' references non-existent dependency target '{dep_id}'."
                    )

        # Step 3: Cycle Detection via 3-color DFS
        self._detect_cycles(target_tasks)

    def _detect_cycles(self, tasks: List[TaskStatus]) -> None:
        """
        Detects circular dependencies using depth-first search cycle detection.

        Raises:
            CyclicDependencyError: If a dependency cycle is found.
        """
        # Map task ID -> dependencies
        dep_graph: Dict[str, List[str]] = {t.id: list(t.dependencies) for t in tasks}

        # 0: UNVISITED, 1: VISITING (in current recursion stack), 2: VISITED
        state: Dict[str, int] = {t.id: 0 for t in tasks}
        path: List[str] = []

        def dfs(node: str) -> None:
            state[node] = 1
            path.append(node)

            for neighbor in dep_graph.get(node, []):
                if state.get(neighbor, 0) == 1:
                    # Cycle found
                    cycle_start_idx = path.index(neighbor)
                    cycle_nodes = path[cycle_start_idx:] + [neighbor]
                    cycle_repr = " -> ".join(cycle_nodes)
                    raise CyclicDependencyError(f"Cyclic dependency detected: {cycle_repr}.")
                elif state.get(neighbor, 0) == 0:
                    dfs(neighbor)

            path.pop()
            state[node] = 2

        for task_id in dep_graph:
            if state[task_id] == 0:
                dfs(task_id)

    # -------------------------------------------------------------------------
    # Dependency Resolution
    # -------------------------------------------------------------------------

    def refresh_dependencies(self) -> None:
        """
        Re-evaluates and updates task readiness based on dependency rules:
        - A task becomes READY only when every dependency is COMPLETED.
        - Tasks with unmet dependencies remain BLOCKED (or transition from PENDING to BLOCKED).
        - Non-pending tasks (RUNNING, COMPLETED, FAILED, SKIPPED) maintain their explicit state.
        """
        completed_ids = {t.id for t in self._tasks if t.status == TaskState.COMPLETED.value}

        for task in self._tasks:
            # Only transition tasks that are awaiting execution
            if task.status in (TaskState.PENDING.value, TaskState.BLOCKED.value, TaskState.READY.value):
                if not task.dependencies:
                    task.status = TaskState.READY.value
                else:
                    all_deps_completed = all(dep in completed_ids for dep in task.dependencies)
                    if all_deps_completed:
                        task.status = TaskState.READY.value
                    else:
                        task.status = TaskState.BLOCKED.value

    # -------------------------------------------------------------------------
    # Persistence Operations
    # -------------------------------------------------------------------------

    def load_tasks(self, path: Optional[Union[str, Path]] = None) -> List[TaskStatus]:
        """
        Safely loads and validates tasks from disk.

        Args:
            path: Optional path override (defaults to self.tasks_path).

        Returns:
            List of loaded and dependency-resolved TaskStatus instances.

        Raises:
            FileNotFoundError: If the specified file does not exist.
            TaskValidationError: If data formatting or schema is invalid.
        """
        target_path = Path(path).resolve() if path else self.tasks_path

        if not target_path.is_file():
            if self.auto_create and not path:
                self._tasks = []
                self._task_map = {}
                self.save_tasks()
                return self._tasks
            raise FileNotFoundError(f"Tasks file not found at '{target_path}'.")

        try:
            with open(target_path, "r", encoding="utf-8") as f:
                raw_data = json.load(f)

            raw_tasks: List[Dict[str, Any]]
            if isinstance(raw_data, list):
                raw_tasks = raw_data
            elif isinstance(raw_data, dict) and "tasks" in raw_data and isinstance(raw_data["tasks"], list):
                raw_tasks = raw_data["tasks"]
            else:
                raise TaskValidationError(
                    f"Tasks payload in '{target_path}' must be a JSON array or an object containing a 'tasks' array."
                )

            loaded_tasks = [TaskStatus.from_dict(item) for item in raw_tasks]
            self.validate_tasks(loaded_tasks)

            self._tasks = loaded_tasks
            self._task_map = {t.id: t for t in loaded_tasks}
            self.refresh_dependencies()

            logger.info("Loaded and validated %d tasks from '%s'.", len(self._tasks), target_path)
            return self._tasks

        except json.JSONDecodeError as exc:
            logger.error("JSON decode error reading tasks from '%s': %s", target_path, exc)
            raise TaskValidationError(f"Invalid JSON syntax in tasks file '{target_path}': {exc}") from exc

    def save_tasks(self, path: Optional[Union[str, Path]] = None) -> Path:
        """
        Atomically saves all tasks to disk using a temporary file and atomic replace.

        Args:
            path: Optional path override (defaults to self.tasks_path).

        Returns:
            Path of saved tasks file.

        Raises:
            TaskValidationError: If task validation fails.
            OSError: If disk write fails.
        """
        target_path = Path(path).resolve() if path else self.tasks_path
        self.validate_tasks(self._tasks)

        target_path.parent.mkdir(parents=True, exist_ok=True)
        temp_path = target_path.with_name(f"{target_path.name}.{os.getpid()}.{time.time_ns()}.tmp")
        payload = [t.to_dict() for t in self._tasks]

        try:
            with open(temp_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
                f.flush()
                os.fsync(f.fileno())

            # Atomic replace with transient lock retry (Windows resiliency)
            last_err = None
            for attempt in range(5):
                try:
                    os.replace(temp_path, target_path)
                    break
                except PermissionError as err:
                    last_err = err
                    time.sleep(0.01 * (attempt + 1))
            else:
                if last_err:
                    raise last_err

            logger.debug("Atomically saved %d tasks to '%s'.", len(self._tasks), target_path)
            return target_path

        except Exception as exc:
            logger.error("Failed to atomically save tasks to '%s': %s", target_path, exc)
            if temp_path.exists():
                try:
                    temp_path.unlink()
                except OSError:
                    pass
            raise

    # -------------------------------------------------------------------------
    # Task Queue Access & Queries
    # -------------------------------------------------------------------------

    def get_task(self, task_id: str) -> TaskStatus:
        """
        Retrieves a task by its unique identifier.

        Args:
            task_id: Task identifier.

        Returns:
            The corresponding TaskStatus object.

        Raises:
            TaskNotFoundError: If task_id is not in the queue.
        """
        if task_id not in self._task_map:
            raise TaskNotFoundError(f"Task with ID '{task_id}' not found in task queue.")
        return self._task_map[task_id]

    def get_all_tasks(self) -> List[TaskStatus]:
        """Returns a copy of all tasks in the queue."""
        return list(self._tasks)

    def get_ready_tasks(self) -> List[TaskStatus]:
        """
        Returns all READY tasks sorted by Priority (CRITICAL > HIGH > MEDIUM > LOW),
        maintaining FIFO ordering within equal priority levels.
        """
        self.refresh_dependencies()
        ready_tasks = [t for t in self._tasks if t.status == TaskState.READY.value]

        # Python's sort is stable; sorting by priority rank preserves original FIFO order
        ready_tasks.sort(key=lambda t: PRIORITY_RANKS[t.priority])
        return ready_tasks

    def get_pending_tasks(self) -> List[TaskStatus]:
        """Returns all tasks currently in PENDING status."""
        return [t for t in self._tasks if t.status == TaskState.PENDING.value]

    def get_completed_tasks(self) -> List[TaskStatus]:
        """Returns all tasks currently in COMPLETED status."""
        return [t for t in self._tasks if t.status == TaskState.COMPLETED.value]

    def get_blocked_tasks(self) -> List[TaskStatus]:
        """Returns all tasks currently in BLOCKED status."""
        self.refresh_dependencies()
        return [t for t in self._tasks if t.status == TaskState.BLOCKED.value]

    def get_failed_tasks(self) -> List[TaskStatus]:
        """Returns all tasks currently in FAILED status."""
        return [t for t in self._tasks if t.status == TaskState.FAILED.value]

    def get_running_tasks(self) -> List[TaskStatus]:
        """Returns all tasks currently in RUNNING status."""
        return [t for t in self._tasks if t.status == TaskState.RUNNING.value]

    def get_next_task(self) -> Optional[TaskStatus]:
        """
        Selects and returns the highest priority READY task according to priority rules:
        CRITICAL > HIGH > MEDIUM > LOW, with FIFO tie-breaking.

        Returns:
            The selected TaskStatus or None if no tasks are READY.
        """
        ready_tasks = self.get_ready_tasks()
        if not ready_tasks:
            return None
        return ready_tasks[0]

    # -------------------------------------------------------------------------
    # Lifecycle Transitions & Mutations
    # -------------------------------------------------------------------------

    def add_task(
        self,
        task: Union[TaskStatus, Dict[str, Any]],
        auto_save: bool = True,
    ) -> TaskStatus:
        """
        Adds a single task to the queue, validates integrity, and refreshes dependencies.

        Args:
            task: TaskStatus instance or dictionary.
            auto_save: Whether to immediately persist changes to disk.

        Returns:
            The added TaskStatus object.
        """
        task_obj = task if isinstance(task, TaskStatus) else TaskStatus.from_dict(task)

        if task_obj.id in self._task_map:
            raise DuplicateTaskIdError(f"Cannot add task: ID '{task_obj.id}' already exists in queue.")

        new_task_list = list(self._tasks) + [task_obj]
        self.validate_tasks(new_task_list)

        self._tasks.append(task_obj)
        self._task_map[task_obj.id] = task_obj
        self.refresh_dependencies()

        if auto_save:
            self.save_tasks()

        logger.info("Added task [%s] (Priority: %s, Status: %s).", task_obj.id, task_obj.priority, task_obj.status)
        return task_obj

    def add_tasks(
        self,
        tasks: List[Union[TaskStatus, Dict[str, Any]]],
        auto_save: bool = True,
    ) -> List[TaskStatus]:
        """
        Adds multiple tasks to the queue with atomic validation.

        Args:
            tasks: List of TaskStatus objects or task dictionaries.
            auto_save: Whether to immediately persist changes to disk.

        Returns:
            List of added TaskStatus objects.
        """
        task_objs = [t if isinstance(t, TaskStatus) else TaskStatus.from_dict(t) for t in tasks]
        new_combined_list = list(self._tasks) + task_objs

        self.validate_tasks(new_combined_list)

        for t in task_objs:
            self._tasks.append(t)
            self._task_map[t.id] = t

        self.refresh_dependencies()

        if auto_save:
            self.save_tasks()

        logger.info("Added %d tasks to the queue.", len(task_objs))
        return task_objs

    def mark_running(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Transitions a task to RUNNING status.

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        task = self.get_task(task_id)
        task.status = TaskState.RUNNING.value
        task.updated_at = datetime.now().isoformat(timespec="seconds")

        if auto_save:
            self.save_tasks()

        logger.info("Marked task [%s] as RUNNING.", task_id)
        return task

    def mark_completed(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Transitions a task to COMPLETED status and unblocks dependent tasks.

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        task = self.get_task(task_id)
        task.status = TaskState.COMPLETED.value
        task.updated_at = datetime.now().isoformat(timespec="seconds")

        # Unblock downstream dependent tasks whose requirements are now satisfied
        self.refresh_dependencies()

        if auto_save:
            self.save_tasks()

        logger.info("Marked task [%s] as COMPLETED.", task_id)
        return task

    def mark_failed(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Handles task failure and increments retry counter:
        - retry_count++
        - If retry_count < max_retries: transitions back to READY
        - Otherwise: transitions permanently to FAILED

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        return self.increment_retry(task_id, auto_save=auto_save)

    def mark_blocked(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Explicitly marks a task as BLOCKED.

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        task = self.get_task(task_id)
        task.status = TaskState.BLOCKED.value
        task.updated_at = datetime.now().isoformat(timespec="seconds")

        if auto_save:
            self.save_tasks()

        logger.info("Marked task [%s] as BLOCKED.", task_id)
        return task

    def mark_skipped(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Transitions a task to SKIPPED status.

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        task = self.get_task(task_id)
        task.status = TaskState.SKIPPED.value
        task.updated_at = datetime.now().isoformat(timespec="seconds")

        if auto_save:
            self.save_tasks()

        logger.info("Marked task [%s] as SKIPPED.", task_id)
        return task

    def increment_retry(self, task_id: str, auto_save: bool = True) -> TaskStatus:
        """
        Increments the retry count of a task and determines if it should
        re-enter the READY queue or transition to permanent FAILED.

        Args:
            task_id: Task identifier.
            auto_save: Whether to persist immediately.

        Returns:
            Updated TaskStatus object.
        """
        task = self.get_task(task_id)
        task.retry_count += 1
        task.updated_at = datetime.now().isoformat(timespec="seconds")

        if task.retry_count < task.max_retries:
            task.status = TaskState.READY.value
            logger.warning(
                "Task [%s] failed attempt %d/%d. Re-queued as READY.",
                task_id,
                task.retry_count,
                task.max_retries,
            )
        else:
            task.status = TaskState.FAILED.value
            logger.error(
                "Task [%s] exhausted maximum retries (%d/%d). Marked as FAILED.",
                task_id,
                task.retry_count,
                task.max_retries,
            )

        if auto_save:
            self.save_tasks()

        return task


if __name__ == "__main__":
    import tempfile

    with tempfile.TemporaryDirectory() as tmp_dir:
        sample_path = Path(tmp_dir) / "tasks.json"
        manager = TaskQueueManager(tasks_path=sample_path)

        manager.add_tasks([
            TaskStatus(id="TASK-01", title="Setup Database", priority="HIGH"),
            TaskStatus(id="TASK-02", title="Implement API", priority="CRITICAL", dependencies=["TASK-01"]),
            TaskStatus(id="TASK-03", title="Write Documentation", priority="LOW"),
        ])

        print(f"Initial Ready Tasks: {[t.id for t in manager.get_ready_tasks()]}")
        next_task = manager.get_next_task()
        print(f"Next Task: {next_task.id} (Priority: {next_task.priority})")

        manager.mark_running(next_task.id)
        manager.mark_completed(next_task.id)

        print(f"Ready Tasks after TASK-01 completed: {[t.id for t in manager.get_ready_tasks()]}")
        next_task = manager.get_next_task()
        print(f"Next Task: {next_task.id} (Priority: {next_task.priority})")
